version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8080:80

  servidor1:
    build:
      context: ./Servidor1
      dockerfile: Dockerfile
    container_name: servidor1
    ports:
      - 8081:5000

  servidor2:
    build:
      context: ./Servidor2
      dockerfile: Dockerfile
    container_name: servidor2
    ports:
      - 8082:5000

  servidor3:
    build:
      context: ./Servidor3
      dockerfile: Dockerfile
    container_name: servidor3
    ports:
      - 8083:5000

  locust:
    image: locustio/locust:latest
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - C:\Users\APP DISTRIBUIDAS\Desktop\Trabajos en clase\VS\Balanceo de carga:/mnt/locust
    command: ["-f","/mnt/locust/locustfile.py"]